# Generated by Django 2.2.4 on 2019-10-24 11:07

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=30)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('desc', models.CharField(default='', max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('Sname', models.CharField(default='', max_length=70)),
                ('pub_date', models.DateField(default='')),
                ('Singer', models.CharField(default='', max_length=20)),
                ('disc', models.CharField(default='', max_length=500)),
                ('link', models.URLField(max_length=150)),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='songs/')),
            ],
        ),
    ]
