# Generated by Django 2.2.4 on 2019-10-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_music_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song',
            field=models.FileField(default='', upload_to='songs/'),
        ),
    ]
